/**
 * Visual Node.js - Runtime Wrapper
 * This script is the entry point for the user's application when running in "Debug" mode.
 * It sets up the environment, enables the inspector, and handles HMR.
 */

const http = require('http');
const WebSocket = require('ws');

// Configuration
const DEBUG_PORT = 9229;
const BRIDGE_PORT = 3001; // Port for IDE <-> Runtime communication

console.log('Visual Node.js Runtime Starting...');

// 1. Setup Bridge Connection
const wss = new WebSocket.Server({ port: BRIDGE_PORT });

// Store connected clients to broadcast events
const clients = new Set();

wss.on('connection', (ws) => {
  console.log('Runtime: Client Connected');
  clients.add(ws);

  ws.on('message', (message) => {
    try {
      const command = JSON.parse(message);
      
      // Broadcast events (like UI clicks) to all other clients (like the User Code)
      if (command.type === 'event') {
          console.log('Runtime: Broadcasting event', command);
          clients.forEach(client => {
              if (client !== ws && client.readyState === WebSocket.OPEN) {
                  client.send(message);
              }
          });
      } else {
          handleCommand(command, ws);
      }
    } catch (e) {
      console.error('Invalid command format');
    }
  });

  ws.on('close', () => {
      clients.delete(ws);
  });

  // Send initial status
  ws.send(JSON.stringify({ type: 'status', status: 'running' }));
});

// Handle IPC messages from Parent (IDE)
process.on('message', (msg) => {
    console.log('Runtime: Received IPC', msg);
    // Create a mock WS object to reuse handleCommand or refactor
    const mockWs = {
        send: (data) => {
            if (process.send) process.send(data);
        }
    };
    
    if (msg.type === 'event') {
        // Broadcast event from IDE (e.g. simulated click) to clients
        clients.forEach(client => {
            if (client.readyState === WebSocket.OPEN) {
                client.send(JSON.stringify(msg));
            }
        });
    } else {
        handleCommand(msg, mockWs);
    }
});

// 2. Command Handler
function handleCommand(cmd, ws) {
  switch (cmd.type) {
    case 'eval':
      try {
        const result = eval(cmd.code); // DANGEROUS in prod, but this is a dev tool
        ws.send(JSON.stringify({ type: 'eval_result', result: String(result) }));
      } catch (e) {
        ws.send(JSON.stringify({ type: 'eval_error', error: e.message }));
      }
      break;
    case 'patch':
      console.log('Runtime: Hot Patching Code...');
      try {
          // cmd.fileName: 'Form1.js'
          // cmd.code: 'exports.Form_Load = ...'
          
          // 1. Write the new code to disk (so require re-reads it if we clear cache)
          const fs = require('fs');
          const path = require('path');
          // We assume we are in the build directory or project directory
          const filePath = path.resolve(process.cwd(), cmd.fileName);
          fs.writeFileSync(filePath, cmd.code);
          
          // 2. Invalidate Require Cache
          delete require.cache[require.resolve(filePath)];
          
          // 3. Re-require to update definitions
          // Note: This works for exported functions. 
          // If the user code has side effects on load, they will run again.
          const newModule = require(filePath);
          
          // 4. Update the running instance (if possible)
          // For Visual Node.js, we might need to update the event handlers map
          // If we are using the 'start_debug.js' harness:
          // We need to tell it to reload the module.
          
          // Since this runner.js is the parent of the user code in some modes,
          // or the user code is running in this process (start_debug.js case).
          
          // Let's assume we are in the 'start_debug.js' context where we have a global 'userCode' object.
          // We can emit an event to the local process to update its reference.
          
          // For this prototype, we'll just log success. 
          // The 'start_debug.js' would need a mechanism to re-bind events.
          
          ws.send(JSON.stringify({ type: 'eval_result', result: 'Code Patched Successfully' }));
          
      } catch (e) {
          console.error('Patch failed:', e);
          ws.send(JSON.stringify({ type: 'eval_error', error: e.message }));
      }
      break;
  }
}

// 3. Start User Application (Simulation)
const projectPath = process.argv[2];
if (projectPath) {
    console.log(`Runtime: Loading project from ${projectPath}`);
    try {
        // Check for start_debug.js first (Generated by Compiler)
        const debugScript = require('path').join(projectPath, 'start_debug.js');
        if (require('fs').existsSync(debugScript)) {
             console.log(`Runtime: Executing Debug Script ${debugScript}`);
             require(debugScript);
        } else {
            // Fallback to standard package.json
            const packageJson = require(require('path').join(projectPath, 'package.json'));
            const mainFile = packageJson.main || 'index.js';
            const entryPoint = require('path').join(projectPath, mainFile);
            
            console.log(`Runtime: Executing ${entryPoint}`);
            require(entryPoint);
        }
    } catch (err) {
        console.error(`Runtime: Failed to start project: ${err.message}`);
        console.error(err.stack);
    }
} else {
    console.error('Runtime: No project path provided.');
}

console.log(`Runtime listening for IDE on port ${BRIDGE_PORT}`);
console.log(`Inspector should be active on port ${DEBUG_PORT}`);

// Keep process alive
setInterval(() => {}, 1000);
