/**
 * Visual Node.js - IntelliSense Generator
 * Generates TypeScript definition files (.d.ts) for the project to enable
 * auto-completion in Monaco Editor.
 */

class IntelliSenseGenerator {
  /**
   * Generates the global definition file for the project controls.
   * @param {Array} controls - List of controls on the form.
   * @returns {string} The content of the .d.ts file.
   */
  generateDefinitions(controls) {
    const controlDefs = controls.map(c => {
        // Map control types to their interface definitions
        const type = this.mapControlType(c.type);
        return `declare const ${c.id}: ${type};`;
    }).join('\n');

    const commonDefs = `
interface Control {
    id: string;
    left: number;
    top: number;
    width: number;
    height: number;
    visible: boolean;
}

interface Button extends Control {
    caption: string;
    click(): void;
}

interface TextBox extends Control {
    text: string;
    change(): void;
}

interface Label extends Control {
    caption: string;
}

// Global App Object
declare const app: {
    on(event: string, callback: Function): void;
};
`;

    return `
// Auto-generated by Visual Node.js
${commonDefs}

// Form Controls
${controlDefs}
`;
  }

  mapControlType(type) {
      switch (type) {
          case 'Button': return 'Button';
          case 'TextBox': return 'TextBox';
          case 'Label': return 'Label';
          default: return 'Control';
      }
  }
}

module.exports = new IntelliSenseGenerator();
